window.AxesTicks = {
    "description": [
        "tick_info_list: list<tick_info>",
        "   tick_info: list<frac (Number), tick_length (Number), tick_style,",
        "       tick_color, tick_stroke_width,",
        "       label_style, label_text, label_color",
        "       label_font_size, label_dist>"
    ],
    "x_axis_tick_info": [
        [
          0.1,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.1",
          "blue",
          "10px",
          25
        ],
        [
          0.2,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.2",
          "blue",
          "10px",
          25
        ],
        [
          0.3,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.3",
          "blue",
          "10px",
          25
        ],
        [
          0.4,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.4",
          "blue",
          "10px",
          25
        ],
        [
          0.5,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.5",
          "blue",
          "10px",
          25
        ],
        [
          0.6,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.6",
          "blue",
          "10px",
          25
        ],
        [
          0.7,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.7",
          "blue",
          "10px",
          25
        ],
        [
          0.8,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.8",
          "blue",
          "10px",
          25
        ],
        [
          0.9,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "0.9",
          "blue",
          "10px",
          25
        ],
        [
          1.0,
          15,
          "bottom",
          "black",
          1,
          "bottom",
          "1.0",
          "blue",
          "10px",
          25
        ]
    ],
    "y_axis_tick_info": [
    ]
}
